const LOCATIONS = {
  "Spyfall - Set Extins (30 Locatii + Roluri)": [],
  "Parc de Trambuline Indoor": ["Instructor de sarituri", "Copil entuziasmat", "Parinte stresat", "Casier", "Administrator sala", "Medic de urgenta", "Fotograf", "Antrenor de parkour", "Curier cu livrare", "Angajat la curatenie"],
  "Studiou de podcast": ["Gazda podcast", "Invitat special", "Tehnician audio", "Cameraman", "Editor", "Producator", "Intern stagiar", "Manager de social media", "Agent de publicitate", "Fan in public"],
  "Festival de muzica": ["DJ", "Fan extaziat", "Agent de paza", "Vanzator de mancare", "Organizator", "Artist pe scena", "Medic voluntar", "Fotograf", "Influencer", "Vanzator de suveniruri"],
  "Escape Room": ["Jucator panicat", "Liderul echipei", "Operatorul camerei", "Designerul jocului", "Manager", "Observator", "Instalator tehnic", "Actor in rol special", "Ingrijitor", "Client plictisit"],
  "Salon de tatuaje": ["Artist tatuator", "Client", "Intern in ucenicie", "Prieten al clientului", "Casier", "Manager", "Designer grafic", "Curier de cerneala", "Inspector sanitar", "Influencer"],
  "Cafenea pentru pisici": ["Barista", "Vizitator iubitor de pisici", "Pisica vedeta", "Manager", "Voluntar", "Fotograf", "Client alergic", "Proprietar", "Blogger", "Livrator de mancare pentru animale"],
  "Studio de streaming pentru jocuri": ["Streamer", "Moderator de chat", "Cameraman", "Tehnician", "Gamer profesionist", "Invitat special", "Cosplayer", "Follower VIP", "Donator anonim", "PR manager"],
  "Centru spa de lux": ["Maseur", "Client relaxat", "Receptioner", "Terapeut facial", "Instructor de yoga", "Manager", "Personal pentru sauna", "Decorator de aromaterapie", "Bucatar vegan", "Influencer wellness"],
  "Bar tematic cu VR": ["Jucator VR", "Barman", "Gazda", "Manager tehnic", "Client confuz", "Prieten al jucatorului", "Dezvoltator VR", "Tester beta", "Instalator de echipamente", "Fotograf"],
  "Depozit Amazon": ["Ambalator", "Robot logistic", "Supervizor", "Sofer de livrare", "Manager de tura", "Angajat nou", "Inspector de calitate", "Muncitor epuizat", "Tehnician IT", "Agent de HR"],
  "Showroom auto electric": ["Vanzator", "Client bogat", "Mecanic", "Test driver", "Consultant financiar", "Specialist in incarcare", "Influencer", "Agent de vanzari online", "Livrator", "Fotograf auto"],
  "Teren de paintball": ["Jucator camuflat", "Arbitru", "Manager", "Casier", "Muncitor la reincarcare", "Fotograf", "Jucator ranit", "Fan", "Instructor de strategie", "Curatator de echipamente"],
  "Barbershop urban": ["Frizer", "Client fidel", "Manager", "Intern", "Vlogger", "Stilist de barba", "Vecin curios", "Influencer local", "Casier", "Om de PR"],
  "Showroom Apple": ["Consultant tech", "Client confuz", "Specialist iPhone", "Specialist Mac", "Casier", "Manager de tura", "Copil jucaus", "Vlogger", "Reparator", "Angajat nou"],
  "Aeroport spatial (futurist)": ["Pilot de nava", "Tehnician", "Turist spatial", "Ofiter de frontiera", "Navigator", "Controlor de zbor", "Inginer propulsie", "Robot asistent", "Manager de hangar", "Jurnalist"],
  "Cartier general al unui startup": ["CEO", "Programator", "Designer UX", "Intern obosit", "Cofondator", "Manager de produs", "Consultant extern", "Agent de vanzari", "Fotograf de branding", "Livrator de pizza"],
  "Croaziera de lux": ["Capitan", "Turist", "Bucatar", "Animator", "Barman", "Camerist", "Coordonator excursii", "Ghid", "DJ", "Maseur"],
  "Targ de Craciun": ["Mos Craciun", "Copil incantat", "Vanzator de vin fiert", "Decorator", "Fotograf", "Vizitator", "Muzician", "Voluntar", "Artist handmade", "Pompier"],
  "Baza subacvatica": ["Biolog marin", "Scafandru", "Capitan", "Navigator", "Tehnician de presiune", "Robot subacvatic", "Medic", "Spion infiltrat", "Cercetator", "Bucatar"],
  "Studiou de filmare TikTok": ["Influencer", "Coregraf", "Cameraman", "Creator de continut", "Editor video", "Manager de PR", "Fan in culise", "Sponsor", "Makeup artist", "Creator de sunete"],
  "Laborator de robotica": ["Inginer robotic", "Tester", "Student in practica", "Profesor", "AI researcher", "Programator", "Mecanic", "Fotograf", "Jurnalist", "Agent guvernamental"],
  "Fabrica de ciocolata": ["Maestru ciocolatier", "Ambalator", "Vizitator", "Turist", "Manager", "Inspector sanitar", "Curier", "Bucatar", "Mecanic utilaj", "Gustator oficial"],
  "Teren de drifting auto": ["Pilot de drift", "Mecanic", "Fotograf", "Jurnalist auto", "Fan", "Instructor", "Organizator", "Vanzator de piese", "Ambulantier", "DJ"],
  "Turn de observatie astronomica": ["Astronom", "Vizitator", "Elev in practica", "Tehnician", "Ghid turistic", "Fotograf de stele", "Cercetator", "Paznic", "Specialist telescop", "Pasare de noapte"],
  "Galerie NFT": ["Artist digital", "Colectionar", "Influencer cripto", "Vizitator", "Developer blockchain", "Critic de arta", "Hacker", "Gazda", "Fotograf", "Investitor"],
  "Restaurant in intuneric total": ["Chelner cu ochelari cu infrarosu", "Client curios", "Bucatar", "Manager", "Ghid", "Casier", "Muzician", "Influencer culinar", "Tehnician iluminat", "Recenzor"],
  "Gradina botanica verticala": ["Botanist", "Turist", "Fotograf", "Elev", "Ghid", "Manager de spatiu verde", "Gradinar", "Artist florar", "Biolog", "Voluntar"],
  "Studio de dublaj pentru desene animate": ["Actor de voce", "Regizor", "Editor de sunet", "Animator", "Asistent", "Manager de proiect", "Personaj animat", "Client", "Vizitator", "Traducator"],
  "Ambulanta in misiune": ["Paramedic", "Sofer", "Pacient", "Asistent", "Doctor la telefon", "Dispecer", "Politist", "Ranit", "Martor", "Paznic de spital"],
  "Repetitie pentru concert rock": ["Vocalist", "Chitarist", "Tobosar", "Manager", "Inginer de sunet", "Fan invitat", "Bodyguard", "Fotograf", "Technician lumini", "Roadie"],
};

export default LOCATIONS;